# Generated by Django 4.1.7 on 2023-03-03 22:59

from django.db import migrations, models
import django.db.models.deletion
import menuapp.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Menu or item name. Must be unique for a top level element.', max_length=50)),
                ('path', models.CharField(blank=True, help_text='Existing Django path or path name. A path has to start with "/" symbol. Can be empty for a top level element.', max_length=100, validators=[menuapp.validators.validate_path])),
                ('parent', models.ForeignKey(blank=True, help_text='Parent item. Leave empty to create a top level element.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menuapp.menuitem')),
            ],
        ),
    ]
